=== ConsenSys/panvala/api/schemas/proposal.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://panvala.com/schemas/proposal.json",
    "title": "Proposal",
    "description": "A Panvala proposal, POSTed to proposals endpoint",
    "type": "object",
    "properties": {
        "title": {
            "description": "The title of the proposal",
            "type": "string",
            "minLength": 1,
            "maxLength": 80
        },
        "summary": {
            "description": "A short summary of the proposal",
            "type": "string",
            "minLength": 1
        },
        "tokensRequested": {
            "description": "The number of tokens requested for the work, in the token base unit",
            "type": "string",
            "pattern": "^[0-9]+$",
            "bigNumber": true
        },
        "firstName": {
            "description": "The proposer's first name",
            "type": "string",
            "minLength": 1
        },
        "lastName": {
            "description": "The proposer's last name",
            "type": "string",
            "minLength": 1
        },
        "email": {
            "description": "The proposer's email address",
            "type": "string",
            "minLength": 1,
            "format": "email"
        },
        "github": {
            "description": "The proposer's github handle",
            "type": "string",
            "minLength": 1
        },
        "website": {
            "description": "The proposer's (team) website",
            "type": "string",
            "format": "uri"
        },
        "projectPlan": {
            "description": "The team's plan for the project",
            "type": "string"
        },
        "projectTimeline": {
            "description": "The team's projected timeline for the project",
            "type": "string"
        },
        "teamBackgrounds": {
            "description": "Backgrounds of the team members",
            "type": "string"
        },
        "totalBudget": {
            "description": "The anticipated budget for the project",
            "type": "string"
        },
        "otherFunding": {
            "description": "Any other funding the team already has",
            "type": "string"
        },
        "awardAddress": {
            "description": "The address where the grant should be delivered, if the proposal is accepted",
            "type": "string",
            "pattern": "^0x[a-fA-F0-9]{40}$"
        }
    },
    "required": ["title", "summary", "tokensRequested", "firstName", "email", "totalBudget", "otherFunding",
        "awardAddress"
    ]
}

=== ConsenSys/panvala/api/data/1-proposal.json
{
    "title": "An amazing proposal",
    "summary": "All sorts of amazing things",
    "tokensRequested": "200000000000000000000000",
    "firstName": "John",
    "lastName": "Crypto",
    "email": "jc@eth.io",
    "github": "jcrypto",
    "website": "jc.io",
    "projectPlan": "2019 is gonna launch",
    "projectTimeline": "2020 is gonna moon",
    "teamBackgrounds": "I do this. She does that.",
    "totalBudget": "$1,000,000 for this. $500,000 for that.",
    "otherFunding": "none",
    "awardAddress": "0xD09cc3Bc67E4294c4A446d8e4a2934a921410eD7"
}

=== ConsenSys/panvala/api/data/2-proposal.json
{
    "title": "Another amazing proposal",
    "summary": "You won't even believe it",
    "tokensRequested": "300000000000000000000000",
    "firstName": "Sarah",
    "lastName": "Ethers",
    "email": "sarah@eth.io",
    "github": "sethers",
    "website": "se.io",
    "projectPlan": "2019 is gonna be good",
    "projectTimeline": "2020 is gonna be great",
    "teamBackgrounds": "I do this. He does that.",
    "totalBudget": "$2,000,000 for this. $100,000 for that.",
    "otherFunding": "n/a",
    "awardAddress": "0xD09cc3Bc67E4294c4A446d8e4a2934a921410eD7"
}
